import type { Service } from "@/types";

export const services: Service[] = [
  {
    name: "Desvanecido",
    description: "Corte degradado progresivo desde la parte superior hacia los lados y la nuca.",
    price: 100,
    duration: "1 hora",
    image: "/images/services/desvanecido.jpg",
  },
  {
    name: "Corte Normal",
    description: "Corte tradicional clásico, limpio y profesional.",
    price: 100,
    duration: "1 hora",
    image: "/images/services/corte-normal.jpg",
  },
  {
    name: "Corte a Tijera",
    description: "Corte artesanal realizado completamente con tijeras para un acabado natural.",
    price: 100,
    duration: "1 hora",
    image: "/images/services/corte-tijera.jpg",
  },
  {
    name: "Delineado de Barba",
    description: "Perfilado y delineado profesional de barba para un look definido.",
    price: 50,
    duration: "20 min",
    image: "/images/services/delineado-barba.jpg",
  },
  {
    name: "Desvanecido de Barba",
    description: "Degradado profesional en la barba para un acabado moderno.",
    price: 35,
    duration: "15 min",
    image: "/images/services/desvanecido-barba.jpg",
  },
  {
    name: "Limpieza de contorno",
    description: "Limpieza de contorno facial y cuidado de la piel.",
    price: 30,
    duration: "20 min",
    image: "/images/services/limpieza.jpg",
  },
  {
    name: "Pigmentación",
    description: "Pigmentación capilar para disimular calvicie o dar densidad visual.",
    price: 30,
    duration: "25 min",
    image: "/images/services/pigmentacion.jpg",
  },
  {
    name: "Afeitado con Navaja",
    description: "Afeitado tradicional con navaja para un acabado suave y profesional.",
    price: 40,
    duration: "25 min",
    image: "/images/services/afeitado-navaja.jpg",
  },
  {
    name: "Limpieza de Ceja",
    description: "Perfilado y limpieza profesional de cejas.",
    price: 20,
    duration: "10 min",
    image: "/images/services/limpieza-ceja.jpg",
  },
  {
    name: "Grecas",
    description: "Diseños artísticos rasurados o dibujados en los laterales o parte posterior del cabello.",
    duration: "15 min",
    image: "/images/services/grecas.jpg",
    isCustomPriced: true,
    customPrice: "Precio a consultar",
  },
];
